config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  mount Flipper::UI.app(Flipper) => "/flipper"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: "churps#index"
    end
    unauthenticated :user do
      root to: "devise/registrations#new", as: :unauthenticated_root
    end
  end
  resources :users, only: %i[index show] do
    member do
      get :following, :followers, :verified_followers, :followers_you_know
    end
  end

  # authenticate :user, ->(u) { u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  get ":slug/status/:churp_id", to: "churps#show", as: "show_churp"
  resources :churps do
    resources :comments, only: %i[create destroy]
    member do
      post :rechurp
    end
    post "like", to: "churps#like" # /churps/:id/like
  end

  resources :profiles do
    member do
      post :follow, :unfollow
    end
  end
  resources :relationships, only: %i[create destroy]

  resources :mentions, only: %i[index]
  resources :notifications, only: %i[index]

  get "search", to: "search#index"
  get "search/hashtags", to: "search#search_hashtags"
  post "search/suggestions", to: "search#suggestions", as: "search_suggestions"

  get "/tos", to: "static#terms_of_service", as: :terms_of_service
  get "/terms_of_service", to: redirect("/terms_of_service")

  get "/privacy", to: "static#privacy_policy", as: :privacy_policy
  get "/privacy-policy", to: redirect("/privacy-policy")

  get "/cookies", to: "static#cookie_policy", as: :cookie_policy
  get "/cookie_policy", to: redirect("/cookie-policy")

  get "/ads", to: "static#ads_info", as: :ads_info
  get "/ads_info", to: redirect("/ads-info")

  get "/about", to: "static#about", as: :about

  get "/test", to: "static#test", as: :test

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up", to: "rails/health#show", as: :rails_health_check

  # unless Rails.env.development?
  #   get 'errors/not_found'
  #   get 'errors/internal_server_error'

  #   match '/404', to: 'errors#not_found', via: :all
  #   match '/500', to: 'errors#internal_server_error', via: :all
  # end
end

app/models/churp.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: churps
#
#  id            :bigint           not null, primary key
#  body          :text
#  rechurp_count :integer          default(0)
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  churp_id      :integer
#  user_id       :bigint           not null
#
# Indexes
#
#  index_churps_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Churp < ApplicationRecord
  belongs_to :user

  belongs_to :churp, optional: true, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  # TODO: This is for the analytics feature on a churp.
  #       The logic for this needs to be rewitten into a model
  #       insead of a tracking pixel. (stupid idea)
  # has_many :views
  has_many :churp_hash_tags, dependent: :destroy
  has_many :hash_tags, through: :churp_hash_tags, dependent: :destroy
  has_many :notifications, as: :recipient, dependent: :destroy

  has_rich_text :content
  has_one_attached :churp_pic

  validates :churp_pic, acceptable_image: true
  validates :content, presence: true
  validates :content, churp_length: true

  after_create :create_hash_tags
  after_create :broadcast_churp
  after_commit :broadcast_notifications

  scope :search_hashtags, ->(query) { joins(:hash_tags).where(hash_tags: { name: query }) }

  def churp_type
    if churp_id? && content?
      "rechurp"
    else
      "churp"
    end
  end

  def create_hash_tags
    extract_name_hash_tags.each do |name|
      hash_tags.create(name:)
    end
  end

  def extract_name_hash_tags
    content.to_s.scan(/#\w+/).map { |name| name.delete("#") }
  end

  private

  def broadcast_churp
    ActionCable.server.broadcast("churps_channel", rendered_churp)
  end

  def rendered_churp
    ApplicationController.renderer.render(
      partial: "churps/churp",
      locals: { churp: self }
    )
  end

  def broadcast_notifications
    BroadcastNotificationsService.call(self)
  end
end

app/controllers/churps_controller.rb
# frozen_string_literal: true

class ChurpsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_churp, only: %i[show edit update destroy like rechurp]

  def index
    @pagy, @churps = pagy(Churp.order(created_at: :desc), items: 15)
    @churp = current_user.churps.new

    render "scrollable_list" if params[:page]
  end

  # GET /churps/1
  # GET /churps/1.json
  def show
    @user = User.friendly.find(params[:slug])
    @comment = current_user.comments.new
    @comments = @churp.comments.recent_comments
  end

  # GET /churps/new
  def new
    @churp = current_user.churps.build
  end

  # GET /churps/1/edit
  def edit
  end

  # POST /churps
  # POST /churps.json
  def create
    @churp = Churp.new(churp_params.merge(user: current_user))
    respond_to do |format|
      if @churp.save
        format.html { redirect_to root_path, notice: "churp was successfully created." }
        format.json { render :show, status: 201, location: @churp }
      else
        format.html { redirect_back fallback_location: @churp, alert: "Could not churp" }
        format.json { render json: @churp.errors, status: 422 }
      end
    end
  end

  # PATCH/PUT /churps/1
  # PATCH/PUT /churps/1.json
  def update
    respond_to do |format|
      if @churp.update(churp_params)
        format.html { redirect_to @churp, notice: "churp was successfully updated." }
        format.json { render :show, status: 200, location: @churp }
      else
        format.html { render :edit }
        format.json { render json: @churp.errors, status: 422 }
      end
    end
  end

  # DELETE /churps/1
  # DELETE /churps/1.json
  def destroy
    @churp.destroy
    respond_to do |format|
      format.html { redirect_to churps_url, notice: "churp was successfully destroyed." }
      format.json { head 204 }
    end
  end

  def like
    create_like_for_churp

    respond_to do |format|
      format.turbo_stream { render_turbo_like_partial }
      format.html { redirect_to churps_path }
    end
  end

  def rechurp
    @rechurp = current_user.churps.new(body: @churp.content, churp_id: @churp.id)
    increment_count = @rechurp.rechurp_count + 1
    @rechurp.update(rechurp_count: increment_count)

    respond_to do |format|
      if @rechurp.save
        format.html { redirect_to churps_path, notice: "Rechurp was successful" }
      else
        format.html { redirect_to churps_path, notice: "Could not rechurp" }
      end
    end
  end

  private

  def create_like_for_churp
    current_user.likes.create(likeable: @churp)
  end

  def render_turbo_like_partial
    render turbo_stream: turbo_stream.replace(
      "like_#{@churp.id}",
      partial: "churps/shared/likes",
      locals: {churp: @churp}
    )
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_churp
    @churp = Churp.find(params[:id] || params[:churp_id])
  end

  # Never trust a big booty and a smile
  def churp_params
    params.require(:churp).permit(:content, :churp_id, :churp_pic)
  end
end

app/helpers/churps_helper.rb
# frozen_string_literal: true

module ChurpsHelper
  def share_icon_class(options = {})
    "flex-1 flex items-center dark:text-white text-xs text-gray-400 hover:text-green-400 " \
      "dark:hover:text-green-400 transition duration-350 ease-in-out #{options[:extended_classes]}"
  end
end

app/views/churps/shared/_analytics.html.erb
<div class="flex-1 flex items-center dark:text-white text-xs text-gray-400 hover:text-red-600 dark:hover:text-red-600 transition duration-350 ease-in-out">
  
  <%= turbo_frame_tag "churp"  do %>
      <div class="flex flex-row items-center">
        <svg width="24px" height="24px" viewBox="0 0 24 24" fill="currentColor" class="fill-white">
          <path fill-rule="evenodd" clip-rule="evenodd" d="M5.5 18C5.5 17.7239 5.72386 17.5 6 17.5H18C18.2761 17.5 18.5 17.7239 18.5 18C18.5 18.2761 18.2761 18.5 18 18.5H6C5.72386 18.5 5.5 18.2761 5.5 18Z" fill="#fff"/>
          <rect x="6.5" y="11.5" width="3" height="7" rx="0.5" fill="#fff"/>
          <rect x="10.5" y="5.5" width="3" height="13" rx="0.5" fill="#fff"/>
          <rect x="14.5" y="8.5" width="3" height="10" rx="0.5" fill="#fff"/>
        </svg>
          <div id="<%= dom_id churp %>">
            <%= content_tag(:div, "", data: {
                controller: "",
                churp_id: churp.id,
                churp_id_value: churp.id,
                view_churps_target: 'count'
            }) %>
            <%#= turbo_stream_from churp, :analytics, channel: ViewChurpsChannel %>
          </div>
      </div>
  <% end %>
</div>

app/views/churps/shared/_comments.html.erb
<div class="flex-1 flex items-center dark:text-white text-xs text-gray-400 hover:text-vividSkyBlueblue dark:hover:text-vividSkyBlue transition duration-350 ease-in-out">
  <svg viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 mr-2">
    <g>
      <path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z"></path>
    </g>
  </svg>
  <%= number_to_human(churp.comments.count, 
      precision: 1,
      round_mode: :down,
      significant: false,
      format: '%n%u',
      units: { thousand: 'K', million: 'M', billion: 'B' }) %>
</div>

app/views/churps/shared/_likes.html.erb
<div class="flex-1 flex items-center dark:text-white text-xs text-gray-400 hover:text-red-600 dark:hover:text-red-600 transition duration-350 ease-in-out">
  <%#= turbo_stream_from churp, :likes %>
  <%= turbo_frame_tag "like_#{churp.id}"  do %>
    <%= link_to churp_like_path(churp),
        data: {turbo_method: :post},
        class: 'z-0' do %>
      <div class="flex flex-row items-center">
        <svg viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 mr-2">
          <g>
            <path d="M12 21.638h-.014C9.403 21.59 1.95 14.856 1.95 8.478c0-3.064 2.525-5.754 5.403-5.754 2.29 0 3.83 1.58 4.646 2.73.814-1.148 2.354-2.73 4.645-2.73 2.88 0 5.404 2.69 5.404 5.755 0 6.376-7.454 13.11-10.037 13.157H12zM7.354 4.225c-2.08 0-3.903 1.988-3.903 4.255 0 5.74 7.034 11.596 8.55 11.658 1.518-.062 8.55-5.917 8.55-11.658 0-2.267-1.823-4.255-3.903-4.255-2.528 0-3.94 2.936-3.952 2.965-.23.562-1.156.562-1.387 0-.014-.03-1.425-2.965-3.954-2.965z"></path>
          </g>
        </svg>
        <%= pluralize(churp.likes.count, 'like') %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/churps/shared/_next_page.html.erb
<%= turbo_frame_tag(
      "churps-page-#{@pagy.next}",
      # autoscroll: true,
      loading: :lazy,
      src: pagy_url_for(@pagy, @pagy.next),
      target: "_top"
    ) do %>
  <%= render 'churps/shared/spinner' %>
<% end %>

app/views/churps/shared/_rechurp_button.html.erb
<div class="<%= share_icon_class %>">
  <%#= turbo_stream_from "churp", :rechurp %>
    <%= button_to rechurp_churp_path(churp), method: :post, class: 'flex-1 flex items-center' do  %>
      <svg viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 mr-2">
        <g>
          <path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path>
        </g>
      </svg>
      <%= churp.rechurp_count %>
    <% end %>
</div>

app/views/churps/shared/_share.html.erb
<div class="flex-1 flex items-center dark:text-white text-xs text-gray-400 hover:text-vividSkyBlue dark:hover:text-vividSkyBlue transition duration-350 ease-in-out">
  <svg viewBox="0 0 24 24" fill="currentColor" class="w-5 h-5 mr-2">
    <g>
      <path d="M17.53 7.47l-5-5c-.293-.293-.768-.293-1.06 0l-5 5c-.294.293-.294.768 0 1.06s.767.294 1.06 0l3.72-3.72V15c0 .414.336.75.75.75s.75-.336.75-.75V4.81l3.72 3.72c.146.147.338.22.53.22s.384-.072.53-.22c.293-.293.293-.767 0-1.06z"></path>
      <path d="M19.708 21.944H4.292C3.028 21.944 2 20.916 2 19.652V14c0-.414.336-.75.75-.75s.75.336.75.75v5.652c0 .437.355.792.792.792h15.416c.437 0 .792-.355.792-.792V14c0-.414.336-.75.75-.75s.75.336.75.75v5.652c0 1.264-1.028 2.292-2.292 2.292z"></path>
    </g>
  </svg>
</div>

app/views/churps/shared/_share_icons.html.erb
<div class="z-0 flex items-center justify-center">

  <%# Comments %>
  <%= render 'churps/shared/comments', churp: churp %>

  <%# Rechurp %>
  <%= render 'churps/shared/rechurp_button', churp: churp %>

  <%= render 'churps/shared/likes', churp: churp %>

  <%# Share %>
  <%= render 'churps/shared/share' %>

</div>

app/views/churps/shared/_spinner.html.erb
<!-- Spinner -->
<%# <div class="flex items-center justify-center p-4 border-b border-l border-r border-gray-200 dark:border-gray-700">
  <svg class="w-8 h-8 animate-spin-fast">
    <circle cx="16" cy="16" fill="none" r="14" stroke-width="4" style="stroke: rgb(29, 161, 242); opacity: 0.2"></circle>
    <circle cx="16" cy="16" fill="none" r="14" stroke-width="4" style=" stroke: rgb(29, 161, 242); stroke-dasharray: 80; stroke-dashoffset: 60;"></circle>
  </svg>
</div> %>
<!-- /Spinner -->

app/views/churps/shared/_user_link.html.erb
<div class="user-link flex flex-shrink-0 p-4 pb-0 z-50">
  <div class="flex items-top">
    <div class="user-pic">
      <%= image_tag(avatar_pic(churp.user.profile), class: 'inline-block h-9 w-9 rounded-full') %>
    </div>

    <div class="ml-3">
      <p class="flex items-center text-base leading-6 font-medium text-gray-800 dark:text-white">
        <%= link_to profile_path(churp.user), class: 'hover:underline' do %>
          <%= churp.user.profile&.name %>
        <% end %>

        <span class="ml-1 text-sm leading-5 font-medium text-gray-400 group-hover:text-gray-300 transition ease-in-out duration-150">
          <%= link_to profile_path(churp.user), class: 'hover:underline' do %>
            <%= "#{churp.user.username}" %> 
          <% end %>
          . 
          <%= "#{churp.created_at.strftime("%b  %-d")}" %>
        </span>
      </p>
    </div>

  </div>
</div>