config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  mount Flipper::UI.app(Flipper) => "/flipper"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: "churps#index"
    end
    unauthenticated :user do
      root to: "devise/registrations#new", as: :unauthenticated_root
    end
  end
  resources :users, only: %i[index show] do
    member do
      get :following, :followers, :verified_followers, :followers_you_know
    end
  end

  # authenticate :user, ->(u) { u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  get ":slug/status/:churp_id", to: "churps#show", as: "show_churp"
  resources :churps do
    resources :comments, only: %i[create destroy]
    member do
      post :rechurp
    end
    post "like", to: "churps#like" # /churps/:id/like
  end

  resources :profiles do
    member do
      post :follow, :unfollow
    end
  end
  resources :relationships, only: %i[create destroy]

  resources :mentions, only: %i[index]
  resources :notifications, only: %i[index]

  get "search", to: "search#index"
  get "search/hashtags", to: "search#search_hashtags"
  post "search/suggestions", to: "search#suggestions", as: "search_suggestions"

  get "/tos", to: "static#terms_of_service", as: :terms_of_service
  get "/terms_of_service", to: redirect("/terms_of_service")

  get "/privacy", to: "static#privacy_policy", as: :privacy_policy
  get "/privacy-policy", to: redirect("/privacy-policy")

  get "/cookies", to: "static#cookie_policy", as: :cookie_policy
  get "/cookie_policy", to: redirect("/cookie-policy")

  get "/ads", to: "static#ads_info", as: :ads_info
  get "/ads_info", to: redirect("/ads-info")

  get "/about", to: "static#about", as: :about

  get "/test", to: "static#test", as: :test

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up", to: "rails/health#show", as: :rails_health_check

  # unless Rails.env.development?
  #   get 'errors/not_found'
  #   get 'errors/internal_server_error'

  #   match '/404', to: 'errors#not_found', via: :all
  #   match '/500', to: 'errors#internal_server_error', via: :all
  # end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  protect_from_forgery with: :null_session

  def index
    if params[:q].start_with?("#")
      query = params[:q].delete("#")
      @churps = Churp.search_hashtags(query)
    else
      @churps = Churp.with_all_rich_text.where("body like ?", "%#{params[:q]}%")
    end
  end

  def search_hashtags
    @results = search_for_hashtags

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:
          turbo_stream.update("search",
            partial: "search/index",
            locals: { posts: @results })
      end
    end
  end

  def suggestions
    @results = search_for_hashtags

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream:
          turbo_stream.update("suggestions",
            partial: "search/suggestions",
            locals: { results: @results })
      end
    end
  end

  private

  def search_for_hashtags
    if params[:query].blank?
      HashTag.all
    else
      results = HashTag.search(params[:query],
        fields: [:name],
        match: :word_start,
        boost_by_recency: { created_at: { scale: "7d", decay: 0.5 } },
        limit: 10)
      results.uniq { |r| r[:name] }
    end
  end
end

app/views/search/_form.html.erb
<%= form_with(url: search_hashtags_path, method: :get, class: 'w-full', data: {
    controller: "search",
    action: "keyup->search#suggestions",
    suggestions_url: search_suggestions_path,
}) do |f| %>
  <div class="relative mx-2 w-full">
    <div class="absolute text-gray-600 flex items-center pl-4 h-full cursor-pointer">
      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-mail" width="18" height="18" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
        <path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path>
      </svg>
    </div>
    <%= f.text_field :q, 
      value: "##{params[:q]}", 
      class: 'z-20 w-full py-4 px-3 bg-gray-200 dark:bg-dim-400 border-gray-200 dark:border-dim-400 text-gray-100 focus:bg-gray-100 dark:focus:bg-dim-900 focus:outline-none focus:border focus:ring-vividSkyBlue font-normal h-12 flex items-center pl-12 text-lg rounded-full border shadow',
      data: {
            search_target: "input",
            action: "blur->search#hideSuggestions",
        },
      placeholder: 'Search Churp', autocomplete: "off" %>
    <div id="suggestions" class="absolute w-full mt-2 bg-white rounded-lg shadow-lg"
        data-search-target="suggestions" data-action="click->search#search">
      <%= render partial: "search/suggestions", locals: { results: results } %>
    </div>
  </div>
<% end %>

app/views/search/_suggestions.html.erb
<% if results.any? %>
  <div class="z-20 absolute w-full overflow-y-auto max-h-80 bg-dim-700  dark:text-white rounded-lg scrollbar-hide cursor-pointer transition duration-350 ease-in-out">
    <% results.each do |hashtag| %>
      <div id="suggestions"
           data-controller="search"
           data-search-target="search"
           data-action="click->search#search"
           class="flex flex-row items-center p-4 hover:bg-dim-300">
        <div class="p-2">
          <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-mail" width="18" height="18" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path d="M21.53 20.47l-3.66-3.66C19.195 15.24 20 13.214 20 11c0-4.97-4.03-9-9-9s-9 4.03-9 9 4.03 9 9 9c2.215 0 4.24-.804 5.808-2.13l3.66 3.66c.147.146.34.22.53.22s.385-.073.53-.22c.295-.293.295-.767.002-1.06zM3.5 11c0-4.135 3.365-7.5 7.5-7.5s7.5 3.365 7.5 7.5-3.365 7.5-7.5 7.5-7.5-3.365-7.5-7.5z"></path>
          </svg>
        </div>
        <%= hashtag.name %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/search/index.html.erb
<div class="w-full sm:w-600 h-screen scrollbar-hide">
  
  <%= render 'shared/header', 
      view: :search, 
      name: nil,
      followers: nil,
      following: nil,
      is_active: false %>

    <% @churps.each do |churp| %>
      <%= render ChurpComponents::ChurpBoxComponent.new(churp: churp) %>
    <% end %>
    

    <%#= render 'churps/shared/next_page'%>

</div>