config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  mount Flipper::UI.app(Flipper) => "/flipper"

  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: "churps#index"
    end
    unauthenticated :user do
      root to: "devise/registrations#new", as: :unauthenticated_root
    end
  end
  resources :users, only: %i[index show] do
    member do
      get :following, :followers, :verified_followers, :followers_you_know
    end
  end

  # authenticate :user, ->(u) { u.admin? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  get ":slug/status/:churp_id", to: "churps#show", as: "show_churp"
  resources :churps do
    resources :comments, only: %i[create destroy]
    member do
      post :rechurp
    end
    post "like", to: "churps#like" # /churps/:id/like
  end

  resources :profiles do
    member do
      post :follow, :unfollow
    end
  end
  resources :relationships, only: %i[create destroy]

  resources :mentions, only: %i[index]
  resources :notifications, only: %i[index]

  get "search", to: "search#index"
  get "search/hashtags", to: "search#search_hashtags"
  post "search/suggestions", to: "search#suggestions", as: "search_suggestions"

  get "/tos", to: "static#terms_of_service", as: :terms_of_service
  get "/terms_of_service", to: redirect("/terms_of_service")

  get "/privacy", to: "static#privacy_policy", as: :privacy_policy
  get "/privacy-policy", to: redirect("/privacy-policy")

  get "/cookies", to: "static#cookie_policy", as: :cookie_policy
  get "/cookie_policy", to: redirect("/cookie-policy")

  get "/ads", to: "static#ads_info", as: :ads_info
  get "/ads_info", to: redirect("/ads-info")

  get "/about", to: "static#about", as: :about

  get "/test", to: "static#test", as: :test

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up", to: "rails/health#show", as: :rails_health_check

  # unless Rails.env.development?
  #   get 'errors/not_found'
  #   get 'errors/internal_server_error'

  #   match '/404', to: 'errors#not_found', via: :all
  #   match '/500', to: 'errors#internal_server_error', via: :all
  # end
end

app/views/shared/_flash_notice.html.erb
<% unless flash.empty? %>
  <% flash.each do |type, message| %>
    <div class="<%= flash_classes(type) %>">
      <%= message %>
      <%= alert %>
    </div>
  <% end %>
<% end %>

app/views/shared/_follow_loader.html.erb
<div class="border-b border-gray-200 dark:border-dim-200 p-4 max-w-sm w-full mx-auto">
  <div class="animate-pulse flex space-x-4">
    <div class="rounded-full bg-gray-400 h-12 w-12"></div>
    <div class="flex-1 space-y-4 py-1">
      <div class="h-4 bg-gray-400 rounded w-3/4"></div>
      <div class="space-y-2">
        <div class="h-4 bg-gray-400 rounded"></div>
        <div class="h-4 bg-gray-400 rounded w-5/6"></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <ul class="text-xs text-gray-500 my-4 mx-2">
    <li class="inline-block mx-2">
      <%= link_to 'Terms of Service', terms_of_service_path, class: 'hover:underline' %>
    </li>
    <li class="inline-block mx-2">
      <%= link_to 'Privacy Policy', privacy_policy_path, class: 'hover:underline' %>
    </li>
    <!-- TODO: finish pages
    <li class="inline-block mx-2">
      <a class="hover:underline" href="#">Cookie Policy</a>
    </li>
    <li class="inline-block mx-2">
      <a class="hover:underline" href="#">Ads info</a>
    </li>
    <li class="inline-block mx-2">
      <a class="hover:underline" href="#">More</a>
    </li>
    -->
    <p>
      <li class="inline-block mx-2">© <%= Time.zone.now.year %> Churp</li>
      <li class="inline-block mx-2 text-gray-400"><b><%= version %></li>
    </p>
  </ul>
</footer>

app/views/shared/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Churp" %>
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= action_cable_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag "actiontext", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_header.html.erb
<div class="flex flex-row justify-between items-center px-4 py-3 bg-white dark:bg-dim-900 border-l border-r border-b border-gray-200 dark:border-gray-700">
    <div class="w-full">
    <% if view == '' %>
      <%= link_to root_path do %>
        <div class="flex justify-start">
          <div class="mx-2 text-2xl font-medium rounded-full text-blue-400 hover:bg-gray-800 hover:text-blue-300 float-right">
              <%= render Icons::BackArrowComponent.new %>
          </div>
          <div class="py-2 mx-2">
            <h2 class=" text-xl font-bold text-white"><%= name %></h2>
          </div>
        </div>
      <% end %>
    <% elsif view == :search %>
        <div class="flex flex-row items-center justify-between space-x-1 w-full">
          <%= link_to root_path do %>
            <div class="mx-2 text-2xl font-medium rounded-full text-blue-400 hover:bg-gray-800 hover:text-blue-300 float-right">
              <%= render Icons::BackArrowComponent.new %>
            </div>
          <% end %>
          <div class="flex flex-row-reverse space-x-1 w-full">
            <%= render partial: "search/form", locals: { results: [] } %>
          </div>
        </div>
    <% else %>
      <h2 class="text-gray-800 dark:text-gray-100 font-bold font-sm">
        <%= name.capitalize %>
      </h2>   
    <% end %>
    </div>
</div>

<%= header_links(controller_name, view: view, followers: followers, following: following) %>

app/views/shared/_left_side.html.erb
<!-- Left -->
<div class="w-68 xs:w-88 xl:w-275 h-screen">
  <div class="flex flex-col h-screen xl:pr-3 fixed w-68 xs:w-88 xl:w-275 scrollbar-hide">
    
    <%= render 'shared/logo' %>

    <%= render 'shared/navbar'%>

    <%= render 'shared/user_menu'%>

  </div>
</div>
<!-- /Left -->

app/views/shared/_logo.html.erb
<!-- Logo -->
<a class="flex my-2 justify-center xl:justify-start" href="/">
  <%= image_tag '/images/logo/churp.png', width: "50", height: "50" %>
</a>
<!-- /Logo -->

app/views/shared/_navbar.html.erb
<!-- Nav -->
<nav class="mt-5 scrollbar-hide">
  <a href="/" class="flex items-center justify-center xl:justify-start text-vividSkyBlue mb-8 transition duration-350 ease-in-out">
    <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M22.58 7.35L12.475 1.897c-.297-.16-.654-.16-.95 0L1.425 7.35c-.486.264-.667.87-.405 1.356.18.335.525.525.88.525.16 0 .324-.038.475-.12l.734-.396 1.59 11.25c.216 1.214 1.31 2.062 2.66 2.062h9.282c1.35 0 2.444-.848 2.662-2.088l1.588-11.225.737.398c.485.263 1.092.082 1.354-.404.263-.486.08-1.093-.404-1.355zM12 15.435c-1.795 0-3.25-1.455-3.25-3.25s1.455-3.25 3.25-3.25 3.25 1.455 3.25 3.25-1.455 3.25-3.25 3.25z"></path>
    </svg>
    <span class="hidden xl:block ml-4 font-bold text-md">Home</span>
  </a>

  <a href="#" class="flex items-center justify-center xl:justify-start text-gray-800 dark:text-white hover:text-vividSkyBlue dark:hover:text-vividSkyBlue mb-8 transition duration-350 ease-in-out">
    <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 7.337h-3.93l.372-4.272c.036-.412-.27-.775-.682-.812-.417-.03-.776.27-.812.683l-.383 4.4h-6.32l.37-4.27c.037-.413-.27-.776-.68-.813-.42-.03-.777.27-.813.683l-.382 4.4H3.782c-.414 0-.75.337-.75.75s.336.75.75.75H7.61l-.55 6.327H3c-.414 0-.75.336-.75.75s.336.75.75.75h3.93l-.372 4.272c-.036.412.27.775.682.812l.066.003c.385 0 .712-.295.746-.686l.383-4.4h6.32l-.37 4.27c-.036.413.27.776.682.813l.066.003c.385 0 .712-.295.746-.686l.382-4.4h3.957c.413 0 .75-.337.75-.75s-.337-.75-.75-.75H16.39l.55-6.327H21c.414 0 .75-.336.75-.75s-.336-.75-.75-.75zm-6.115 7.826h-6.32l.55-6.326h6.32l-.55 6.326z"></path>
    </svg>
    <span class="hidden xl:block ml-4 font-bold text-md">Explore</span>
  </a>

  <%= render 'shared/notificaions', user: current_user %>
  <%#= render Nav::NotificationsComponent.new(user: current_user) %>

  <a href="#" class="flex items-center justify-center xl:justify-start text-gray-800 dark:text-white hover:text-vividSkyBlue dark:hover:text-vividSkyBlue mb-8 transition duration-350 ease-in-out">
    <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.25 3.018H4.75C3.233 3.018 2 4.252 2 5.77v12.495c0 1.518 1.233 2.753 2.75 2.753h14.5c1.517 0 2.75-1.235 2.75-2.753V5.77c0-1.518-1.233-2.752-2.75-2.752zm-14.5 1.5h14.5c.69 0 1.25.56 1.25 1.25v.714l-8.05 5.367c-.273.18-.626.182-.9-.002L3.5 6.482v-.714c0-.69.56-1.25 1.25-1.25zm14.5 14.998H4.75c-.69 0-1.25-.56-1.25-1.25V8.24l7.24 4.83c.383.256.822.384 1.26.384.44 0 .877-.128 1.26-.383l7.24-4.83v10.022c0 .69-.56 1.25-1.25 1.25z"></path>
    </svg>
    <span class="hidden xl:block ml-4 font-bold text-md">Messages</span>
  </a>

  <a href="#" class="flex items-center justify-center xl:justify-start text-gray-800 dark:text-white hover:text-vividSkyBlue dark:hover:text-vividSkyBlue mb-8 transition duration-350 ease-in-out">
    <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19.9 23.5c-.157 0-.312-.05-.442-.144L12 17.928l-7.458 5.43c-.228.164-.53.19-.782.06-.25-.127-.41-.385-.41-.667V5.6c0-1.24 1.01-2.25 2.25-2.25h12.798c1.24 0 2.25 1.01 2.25 2.25v17.15c0 .282-.158.54-.41.668-.106.055-.223.082-.34.082zM12 16.25c.155 0 .31.048.44.144l6.71 4.883V5.6c0-.412-.337-.75-.75-.75H5.6c-.413 0-.75.338-.75.75v15.677l6.71-4.883c.13-.096.285-.144.44-.144z"></path>
    </svg>
    <span class="hidden xl:block ml-4 font-bold text-md">Bookmarks</span>
  </a>
  <% if Flipper.enabled?(:lists_feature) %>
  <a href="#" class="flex items-center justify-center xl:justify-start text-gray-800 dark:text-white hover:text-vividSkyBlue dark:hover:text-vividSkyBlue mb-8 transition duration-350 ease-in-out">
    <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
      <g>
        <path d="M19.75 22H4.25C3.01 22 2 20.99 2 19.75V4.25C2 3.01 3.01 2 4.25 2h15.5C20.99 2 22 3.01 22 4.25v15.5c0 1.24-1.01 2.25-2.25 2.25zM4.25 3.5c-.414 0-.75.337-.75.75v15.5c0 .413.336.75.75.75h15.5c.414 0 .75-.337.75-.75V4.25c0-.413-.336-.75-.75-.75H4.25z"></path>
        <path d="M17 8.64H7c-.414 0-.75-.337-.75-.75s.336-.75.75-.75h10c.414 0 .75.335.75.75s-.336.75-.75.75zm0 4.11H7c-.414 0-.75-.336-.75-.75s.336-.75.75-.75h10c.414 0 .75.336.75.75s-.336.75-.75.75zm-5 4.11H7c-.414 0-.75-.335-.75-.75s.336-.75.75-.75h5c.414 0 .75.337.75.75s-.336.75-.75.75z"></path>
      </g>
    </svg>
    <span class="hidden xl:block ml-4 font-bold text-md">Lists</span>
  </a>
  <% end %>

  <%= link_to profile_path(current_user),
      class: "flex items-center justify-center xl:justify-start text-gray-800 dark:text-white hover:text-vividSkyBlue dark:hover:text-vividSkyBlue mb-8 transition duration-350 ease-in-out" do %>
    <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 11.816c1.355 0 2.872-.15 3.84-1.256.814-.93 1.078-2.368.806-4.392-.38-2.825-2.117-4.512-4.646-4.512S7.734 3.343 7.354 6.17c-.272 2.022-.008 3.46.806 4.39.968 1.107 2.485 1.256 3.84 1.256zM8.84 6.368c.162-1.2.787-3.212 3.16-3.212s2.998 2.013 3.16 3.212c.207 1.55.057 2.627-.45 3.205-.455.52-1.266.743-2.71.743s-2.255-.223-2.71-.743c-.507-.578-.657-1.656-.45-3.205zm11.44 12.868c-.877-3.526-4.282-5.99-8.28-5.99s-7.403 2.464-8.28 5.99c-.172.692-.028 1.4.395 1.94.408.52 1.04.82 1.733.82h12.304c.693 0 1.325-.3 1.733-.82.424-.54.567-1.247.394-1.94zm-1.576 1.016c-.126.16-.316.246-.552.246H5.848c-.235 0-.426-.085-.552-.246-.137-.174-.18-.412-.12-.654.71-2.855 3.517-4.85 6.824-4.85s6.114 1.994 6.824 4.85c.06.242.017.48-.12.654z"></path>
    </svg>
    <span class="hidden xl:block ml-4 font-bold text-md">Profile</span>
  
  <% end %>

  <a href="#" class="flex items-center justify-center xl:justify-start text-gray-800 dark:text-white hover:text-vividSkyBlue dark:hover:text-vividSkyBlue mb-8 transition duration-350 ease-in-out">
    <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
      <g>
        <path d="M16.5 10.25c-.965 0-1.75.787-1.75 1.75s.784 1.75 1.75 1.75c.964 0 1.75-.786 1.75-1.75s-.786-1.75-1.75-1.75zm0 2.5c-.414 0-.75-.336-.75-.75 0-.413.337-.75.75-.75s.75.336.75.75c0 .413-.336.75-.75.75zm-4.5-2.5c-.966 0-1.75.787-1.75 1.75s.785 1.75 1.75 1.75 1.75-.786 1.75-1.75-.784-1.75-1.75-1.75zm0 2.5c-.414 0-.75-.336-.75-.75 0-.413.337-.75.75-.75s.75.336.75.75c0 .413-.336.75-.75.75zm-4.5-2.5c-.965 0-1.75.787-1.75 1.75s.785 1.75 1.75 1.75c.964 0 1.75-.786 1.75-1.75s-.787-1.75-1.75-1.75zm0 2.5c-.414 0-.75-.336-.75-.75 0-.413.337-.75.75-.75s.75.336.75.75c0 .413-.336.75-.75.75z"></path>
        <path d="M12 22.75C6.072 22.75 1.25 17.928 1.25 12S6.072 1.25 12 1.25 22.75 6.072 22.75 12 17.928 22.75 12 22.75zm0-20C6.9 2.75 2.75 6.9 2.75 12S6.9 21.25 12 21.25s9.25-4.15 9.25-9.25S17.1 2.75 12 2.75z"></path>
      </g>
    </svg>
    <span class="hidden xl:block ml-4 font-bold text-md">More</span>
  </a>

  <a href="#" class="mx-auto w-11 h-11 xl:w-auto flex items-center justify-center bg-vividSkyBlue hover:bg-cyan-600 py-3 rounded-full text-white font-bold font-sm transition duration-350 ease-in-out mb-10">
    <span class="hidden xl:block font-bold text-md">Churp</span>
  </a>
</nav>
<!-- /Nav -->

app/views/shared/_notificaions.html.erb
<div>
  <a href="/notifications" class="flex items-center justify-center xl:justify-start text-gray-800 dark:text-white hover:text-vividSkyBlue dark:hover:text-vividSkyBlue mb-8 transition duration-350 ease-in-out">
    <div class="relative">
      <svg fill="currentColor" viewBox="0 0 24 24" class="h-6 w-6">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21.697 16.468c-.02-.016-2.14-1.64-2.103-6.03.02-2.532-.812-4.782-2.347-6.335C15.872 2.71 14.01 1.94 12.005 1.93h-.013c-2.004.01-3.866.78-5.242 2.174-1.534 1.553-2.368 3.802-2.346 6.334.037 4.33-2.02 5.967-2.102 6.03-.26.193-.366.53-.265.838.102.308.39.515.712.515h4.92c.102 2.31 1.997 4.16 4.33 4.16s4.226-1.85 4.327-4.16h4.922c.322 0 .61-.206.71-.514.103-.307-.003-.645-.263-.838zM12 20.478c-1.505 0-2.73-1.177-2.828-2.658h5.656c-.1 1.48-1.323 2.66-2.828 2.66zM4.38 16.32c.74-1.132 1.548-3.028 1.524-5.896-.018-2.16.644-3.982 1.913-5.267C8.91 4.05 10.397 3.437 12 3.43c1.603.008 3.087.62 4.18 1.728 1.27 1.285 1.933 3.106 1.915 5.267-.024 2.868.785 4.765 1.525 5.896H4.38z"></path>
      </svg>
      <%= render 'mentions/notification_count', user: user, count: user.unread_notifications.count %>
    </div>
    <div>
      <span class="hidden xl:block ml-4 font-bold text-md">Notifications</span>
    </div>
  </a>
</div>

app/views/shared/_right_side.html.erb
<div class="hidden md:block w-290 lg:w-350 h-screen">
  <div class="flex flex-col fixed overflow-y-auto scrollbar-hide w-290 lg:w-350 h-screen">
    
    <%= render Search::SearchBarComponent.new %>

    <%= render 'shared/whats_happening', popular_hashtags: @popular_hashtags %>

    <div class="bg-gray-50 dark:bg-dim-700 rounded-2xl m-2">
      <h1 class="text-gray-900 dark:text-white text-md font-bold p-3 border-b border-gray-200 dark:border-dim-200">
        Who to follow
      </h1>

      <div class="text-blue-400 text-sm font-normal p-3 border-b border-gray-200 dark:border-dim-200 hover:bg-gray-100 dark:hover:bg-dim-300 cursor-pointer transition duration-350 ease-in-out">
        <div class="flex flex-row justify-between p-2">
          <div class="flex flex-row">
            <img class="w-10 h-10 rounded-full" src="/images/joe_biden.jpg" alt="Joe Biden"/>
            <div class="flex flex-col ml-2">
              <h1 class="text-gray-900 dark:text-white font-bold text-sm">
                Joe Biden
              </h1>
              <p class="text-gray-400 text-sm">@JoeBiden</p>
            </div>
          </div>
          <div class="">
            <div class="flex items-center h-full text-gray-800 dark:text-white">
              <a href="#" class="text-xs font-bold text-vividSkyBlue px-4 py-1 rounded-full border-2 border-vividSkyBlue">Follow</a>
            </div>
          </div>
        </div>
      </div>

      <div class="text-blue-400 text-sm font-normal p-3 border-b border-gray-200 dark:border-dim-200 hover:bg-gray-100 dark:hover:bg-dim-300 cursor-pointer transition duration-350 ease-in-out">
        <div class="flex flex-row justify-between p-2">
          <div class="flex flex-row">
            <img class="w-10 h-10 rounded-full" src="/images/joe_biden.jpg" alt="Joe Biden"/>
            <div class="flex flex-col ml-2">
              <h1 class="text-gray-900 dark:text-white font-bold text-sm">
                Joe Biden
              </h1>
              <p class="text-gray-400 text-sm">@JoeBiden</p>
            </div>
          </div>
          <div class="">
            <div class="flex items-center h-full text-gray-800 dark:text-white">
              <a href="#" class="text-xs font-bold text-vividSkyBlue px-4 py-1 rounded-full border-2 border-vividSkyBlue">Follow</a>
            </div>
          </div>
        </div>
      </div>

      <%#= render 'shared/follow_loader' %>

      <div class="text-vividSkyBlue text-sm font-normal p-3 hover:bg-gray-100 dark:hover:bg-dim-300 cursor-pointer transition duration-350 ease-in-out">
        Show more
      </div>
    </div>

    <%= render 'shared/footer'%>
  </div>
</div>

app/views/shared/_user_menu.html.erb
<%= link_to destroy_user_session_path, 
    data: { "turbo-method": :delete },
    class: "w-14 xl:w-full mx-auto mt-auto flex flex-row justify-between mb-5 rounded-full hover:bg-blue-50 dark:hover:bg-dim-800 p-2 cursor-pointer transition duration-350 ease-in-out" do %>
  <div class="">
    <div class="flex flex-row">
      <%= image_tag(avatar_pic(current_user.profile), class: 'w-10 h-10 rounded-full') %>
      <div class="xl:block flex flex-col ml-2">
        <h1 class="text-gray-800 dark:text-white font-bold text-sm"> <%= current_user.profile&.name%> </h1>
        <p class="text-gray-400 text-sm"><%= current_user.username %></p>
      </div>
    </div>

    <div class="hidden xl:block">
      <div class="flex items-center h-full text-gray-800 dark:text-white">
        <svg viewBox="0 0 24 24" fill="currentColor" class="h-4 w-4 mr-2">
          <g>
            <path d="M20.207 8.147c-.39-.39-1.023-.39-1.414 0L12 14.94 5.207 8.147c-.39-.39-1.023-.39-1.414 0-.39.39-.39 1.023 0 1.414l7.5 7.5c.195.196.45.294.707.294s.512-.098.707-.293l7.5-7.5c.39-.39.39-1.022 0-1.413z"></path>
          </g>
        </svg>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_whats_happening.html.erb
<div class="bg-gray-50 dark:bg-dim-700 rounded-2xl m-2">
  <h1 class="text-gray-900 dark:text-white text-md font-bold p-3 border-b border-gray-200 dark:border-dim-200">
    What’s happening
  </h1>
  
  <% popular_hashtags.each do |k, v| %>
    <%= render TrendingTopicComponent.new(hashtag: k, num_of_churps: v) %>      
  <% end %>

  <div class="text-vividSkyBlue text-sm font-normal p-3 hover:bg-gray-100 dark:hover:bg-dim-300 cursor-pointer transition duration-350 ease-in-out">
    Show more
  </div>
</div>

app/views/shared/timeline_notification.html.erb
<!-- Timeline Notification -->
<div lass="border-b border-gray-200 dark:border-dim-200 bg-gray-50 dark:bg-dim-300 py-2 border-l border-r">
  <div class="flex flex-col items-center justify-center text-center p-6 bg-white dark:bg-dim-900 border-b border-t border-gray-200 dark:border-dim-200 hover:bg-gray-50 dark:hover:bg-dim-300 cursor-pointer transition duration-350 ease-in-out text-blue-400 text-sm">
    <h1 class="dark:text-white text-gray-900 text-2xl font-bold mb-2">
      Customize your view
    </h1>
    <p class="text-gray-500 mb-5">
      Manage your font size, color and background. These settings
      affect all the Twitter accounts on this browser.
    </p>
    <a href="javascript:void(0)" onclick="document.querySelector('html').classList.toggle('dark')" class="mx-auto w-11 h-11 xl:w-48 flex items-center justify-center bg-blue-400 hover:bg-blue-500 py-3 rounded-full text-white font-bold font-sm transition duration-350 ease-in-out">
      <svg fill="currentColor" viewBox="0 0 24 24" class="block xl:hidden h-6 w-6">
        <g>
          <path d="M15.692 11.205l6.383-7.216c.45-.45.45-1.18 0-1.628-.45-.45-1.178-.45-1.627 0l-7.232 6.402s.782.106 1.595.93c.548.558.882 1.51.882 1.51z"></path>
          <path d="M17.45 22.28H3.673c-1.148 0-2.083-.946-2.083-2.11V7.926c0-1.165.934-2.112 2.082-2.112h5.836c.414 0 .75.336.75.75s-.336.75-.75.75H3.672c-.32 0-.583.274-.583.612V20.17c0 .336.26.61.582.61h13.78c.32 0 .583-.273.583-.61v-6.28c0-.415.336-.75.75-.75s.75.335.75.75v6.28c0 1.163-.934 2.11-2.084 2.11z"></path>
        </g>
      </svg>
      <span class="hidden xl:block font-bold text-md">Toggle Dark Mode</span>
    </a>
  </div>
</div>
<!-- /Timeline Notification -->